import ExamNotebook,{ExamCard,ExamQuestion,NotebookConfig} from "../components/ExamNotebook";

const config:NotebookConfig={code:"18",eyebrow:"Prova IFMT 2023 · questões 21 a 30",title:"Mato Grosso",titleAccent:"território e sociedade",description:"Biomas, municípios, hidrografia, migração, economia e território lidos no recorte temporal da última prova, com atenção às fontes e aos dados mutáveis.",tone:"matoGrossoNotebook",scope:"Aspectos naturais, humanos e econômicos de Mato Grosso, além de desenvolvimento sustentável e atualidades territorializadas.",references:["IFMT — Caderno de prova Professor EBTT, Edital nº 166/2023.","IBGE — Cidades e Estados, Contas Regionais e Produção Agrícola Municipal.","INPE/TerraBrasilis — monitoramento dos biomas brasileiros.","SEMA-MT — recursos hídricos e períodos de restrição ao uso do fogo.","SEDEC-MT — perfil econômico, produção agropecuária e logística."]};
const source="IFMT · Professor EBTT · Edital 166/2023";
const questions:ExamQuestion[]=[
{examId:"21",source,prompt:"Observe o mapa abaixo. O bioma em destaque com alto índice de desmatamento ressaltado pelo mapeamento foi:",options:["Mata Atlântica.","Caatinga.","Pantanal.","Cerrado.","Pradarias."],answer:3,explanation:"O contorno destacado ocupa o Brasil central e corresponde ao Cerrado. A identificação depende da distribuição espacial, não apenas da intensidade da legenda.",languageNote:"“Em destaque” retoma a área escura do mapa; “bioma” delimita a categoria pedida.",xray:"Leitura cartográfica: título + contorno + localização.",image:"/exam-diagrams/mt-desmatamento-cerrado.png",imageAlt:"Mapa de incrementos de desmatamento com o Cerrado destacado no Brasil central",caption:"Figura reproduzida da questão 21 do caderno de prova anexado · fonte original indicada: TerraBrasilis/INPE, acesso em 13 maio 2023."},
{examId:"22",source,prompt:"A área do município de Chapada dos Guimarães faz limite com todos os municípios abaixo, EXCETO:",options:["Rosário Oeste.","Cuiabá.","Poconé.","Nova Brasilândia.","Campo Verde."],answer:2,explanation:"Poconé não integra a lista de municípios limítrofes de Chapada dos Guimarães; os demais fazem fronteira municipal com Chapada.",languageNote:"EXCETO transforma a questão em teste de exclusão. “Faz limite” significa contiguidade territorial, não proximidade regional.",xray:"Geografia municipal + comando negativo."},
{examId:"23",source,prompt:"A empresa Cargill inaugurou sua fábrica de premix e nutrição animal da marca Nutron em qual município mato-grossense?",options:["Primavera do Leste.","Várzea Grande.","Rondonópolis.","Sorriso.","Sinop."],answer:3,explanation:"A notícia usada pela prova localiza a unidade em Sorriso. Trata-se de dado econômico-eventual vinculado ao recorte da prova de 2023.",languageNote:"O possessivo “sua” retoma Cargill; o núcleo interrogativo é “em qual município”.",xray:"Atualidade econômica: empresa + unidade + localização."},
{examId:"24",source,prompt:"Sobre a hidrografia de Mato Grosso, analise: I. o estado é drenado pelas bacias Amazônica, Platina e Tocantins-Araguaia; II. a bacia Amazônica drena cerca de dois terços do território e o Teles Pires se une ao Juruena para formar o Tapajós; III. os rios têm regime predominantemente pluvial; IV. o principal divisor de águas é o Planalto/Chapada dos Parecis. Estão corretas:",options:["II e IV apenas.","I, III e IV apenas.","I e II apenas.","III e IV apenas.","I, II, III e IV."],answer:4,explanation:"As quatro afirmações descrevem a organização hidrográfica estadual: três grandes sistemas, predomínio amazônico, regime pluvial e o divisor dos Parecis.",languageNote:"A enumeração reúne escala regional, proporção, regime e relevo; cada item exige um critério próprio.",xray:"Bacia, drenagem, regime e divisor de águas."},
{examId:"25",source,prompt:"Quais quatro produtos representam mais de 93% da riqueza agropecuária de Mato Grosso no recorte apresentado pela prova?",options:["Soja, cana-de-açúcar, algodão e bovinos.","Milho, soja, cana-de-açúcar e café.","Soja, milho, bovinos e algodão.","Soja, bovinos, algodão e madeira.","Milho, soja, madeira e bovinos."],answer:2,explanation:"O conjunto indicado é soja, milho, bovinos e algodão. O percentual é temporal: serve para interpretar a fonte da prova, não como estatística permanente.",languageNote:"As alternativas variam um item por vez; “quatro produtos” pede o conjunto completo, sem substituições.",xray:"Composição econômica + dado dependente de ano-base."},
{examId:"26",source,prompt:"Sobre os fluxos migratórios para Mato Grosso, analise: I. a abertura de rodovias favoreceu ocupação e integração; II. colonização e terras relativamente baratas atraíram migrantes; III. programas governamentais e incentivos estimularam o movimento; IV. entre as décadas de 1970 e 1990 houve forte migração interna. Estão corretas:",options:["I, II e IV apenas.","III e IV apenas.","II e III apenas.","I, III e IV apenas.","I, II, III e IV."],answer:4,explanation:"As quatro proposições integram o mesmo processo de expansão da fronteira agrícola e de ocupação dirigida ocorrido sobretudo na segunda metade do século XX.",languageNote:"Os itens são complementares, não concorrentes: infraestrutura, terra, política pública e cronologia.",xray:"Causas estruturais e período dos fluxos migratórios."},
{examId:"27",source,prompt:"São rios pertencentes à sub-bacia do Tapajós, EXCETO:",options:["Teles Pires.","Aripuanã.","Arinos.","Sangue.","Juruena."],answer:1,explanation:"O Aripuanã integra o sistema do rio Madeira. Teles Pires e Juruena formam o Tapajós; Arinos e Sangue pertencem ao sistema Juruena–Tapajós.",languageNote:"EXCETO exige localizar o único rio pertencente a outro sistema hidrográfico.",xray:"Hierarquia hidrográfica: rio → sub-bacia → bacia."},
{examId:"28",source,prompt:"Sobre queimadas em Mato Grosso, julgue as afirmações da questão original: I. o Cerrado foi o bioma mais afetado no recorte; II. Ribeirão Cascalheira e São Félix do Araguaia lideraram ocorrências e situam-se no Cerrado; III. a Amazônia foi o bioma mais afetado; IV. o estado estabeleceu período proibitivo e restrições ao fogo rural; V. a queima controlada é proibida em perímetros urbanos. Assinale a sequência correta.",options:["F – V – V – V – V.","F – F – V – V – F.","V – F – V – F – V.","V – V – F – F – V.","F – V – F – V – F."],answer:3,explanation:"No recorte noticioso adotado pela prova, I e II são verdadeiras, III e IV falsas e V verdadeira. Datas e regras de período proibitivo devem sempre ser atualizadas em fonte oficial.",languageNote:"I e III são mutuamente incompatíveis; essa oposição já elimina sequências em que ambas recebem o mesmo valor.",xray:"V/F + coerência interna + atualidade ambiental."},
{examId:"29",source,prompt:"Qual município mato-grossense, apresentado como capital nacional do agronegócio, alcançou R$ 11,5 bilhões e a primeira posição no ranking referido pela prova?",options:["Campo Novo do Parecis.","Sorriso.","Sapezal.","Nova Mutum.","Primavera do Leste."],answer:1,explanation:"A matéria tomada como base pela prova identifica Sorriso. Valor e posição pertencem ao ano-base da notícia e precisam de atualização para usos atuais.",languageNote:"O aposto “capital nacional do agronegócio” funciona como pista de identificação do município.",xray:"Ranking municipal com recorte temporal explícito."},
{examId:"30",source,prompt:"Sobre Mato Grosso, analise: I. é o terceiro maior estado em área e limita-se com Pará/Amazonas ao norte, Mato Grosso do Sul ao sul, Goiás/Tocantins a leste e Rondônia/Bolívia a oeste; II. possui extensa faixa de fronteira; III. foi amplamente explorado no século XIX e teve desenvolvimento industrial intenso após 1970; IV. é o quarto maior estado e limita-se com Roraima a oeste; V. destaca-se como fornecedor de matérias-primas, com forte peso agropecuário no PIB e nas exportações. Estão corretas:",options:["I, II e V apenas.","I, II e III apenas.","II, IV e V apenas.","III e IV apenas.","I, II e IV apenas."],answer:0,explanation:"I, II e V são compatíveis com a posição, os limites e a estrutura econômica estadual. III exagera a industrialização e erra o enquadramento histórico; IV erra posição e vizinhança.",languageNote:"Em IV, um único topônimo impossível — Roraima — invalida toda a proposição.",xray:"Localização, fronteira, história econômica e perfil produtivo."}
];
const cards:ExamCard[]=[
{front:"Biomas presentes em Mato Grosso",back:"Amazônia, Cerrado e Pantanal.",tag:"Natureza"},{front:"Como reconhecer o Cerrado no mapa?",back:"Faixa central do Brasil, conectando áreas do Centro-Oeste, Sudeste, Norte e Nordeste.",tag:"Cartografia"},{front:"Chapada dos Guimarães faz limite com Poconé?",back:"Não. Essa é a exceção cobrada na prova.",tag:"Municípios"},{front:"Três grandes sistemas hidrográficos de MT",back:"Amazônico, Tocantins-Araguaia e Platino/Paraguai.",tag:"Hidrografia"},{front:"Formação do Tapajós",back:"Confluência dos rios Teles Pires e Juruena.",tag:"Hidrografia"},{front:"Aripuanã pertence a qual sistema?",back:"Ao sistema do rio Madeira, não ao Tapajós.",tag:"Hidrografia"},{front:"Regime predominante dos rios",back:"Pluvial: vazão condicionada principalmente pelas chuvas.",tag:"Hidrografia"},{front:"Principal divisor de águas estadual",back:"Planalto e Chapada dos Parecis.",tag:"Relevo"},{front:"Quatro produtos do recorte agropecuário",back:"Soja, milho, bovinos e algodão.",tag:"Economia"},{front:"Capital nacional do agronegócio na prova",back:"Sorriso — título e ranking ligados ao ano-base da fonte.",tag:"Economia"},{front:"Vetores da migração 1970–1990",back:"Rodovias, colonização, terras, incentivos públicos e fronteira agrícola.",tag:"Sociedade"},{front:"O que é faixa de fronteira?",back:"Área legal interna paralela à linha internacional, sujeita a regime especial.",tag:"Território"},{front:"Queimadas: cuidado central",back:"Períodos proibitivos e rankings mudam; consultar SEMA/INPE pelo ano da questão.",tag:"Atualidades"},{front:"Dado estrutural x conjuntural",back:"Limites territoriais tendem a ser estáveis; ranking, PIB e queimadas dependem do período.",tag:"Método"},{front:"Questão com EXCETO",back:"Teste cada alternativa contra a categoria e marque a única que fica fora.",tag:"Prova"},{front:"Item V/F contraditório",back:"Use incompatibilidades lógicas entre itens para eliminar sequências antes da memória factual.",tag:"Prova"}
];
export default function Page(){return <ExamNotebook config={config} questions={questions} cards={cards}/>}
