'use client';
import {useMemo,useState} from 'react';
import Link from 'next/link';
import type {StudyQuestion} from '@/lib/study-model';
import {analyzeCorpus,languageSignals,RESEARCH_VERSION} from '@/lib/bank-research';
import './research.css';
type Annotation={concept:string;definition:string;confusion:string;task:string;hypothesis:string;authorship:string;author:string;model:string;evidence:string;references:string};
const empty:Annotation={concept:'',definition:'',confusion:'',task:'',hypothesis:'',authorship:'unknown',author:'',model:'',evidence:'',references:''};
export default function ResearchWorkspace({questions}:{questions:StudyQuestion[]}){
 const [source,setSource]=useState('');const [subject,setSubject]=useState('');const [query,setQuery]=useState('');const [selected,setSelected]=useState('');const [notes,setNotes]=useState<Record<string,Annotation>>({});const [message,setMessage]=useState('');
 const sources=useMemo(()=>[...new Set(questions.map(q=>q.source))].sort(),[questions]);
 const subjects=useMemo(()=>[...new Set(questions.filter(q=>!source||q.source===source).map(q=>q.subject))].sort(),[questions,source]);
 const corpus=useMemo(()=>analyzeCorpus(questions.filter(q=>(!source||q.source===source)&&(!subject||q.subject===subject))),[questions,source,subject]);
 const results=corpus.questions.filter(q=>[q.prompt,...q.options,q.subject].join(' ').toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')));
 const q=corpus.questions.find(q=>q.id===selected)??results[0];const annotation=q?(notes[q.id]??empty):empty;
 function update(key:keyof Annotation,value:string){if(q)setNotes({...notes,[q.id]:{...annotation,[key]:value}});}
 function exportReport(){const payload={version:RESEARCH_VERSION,exportedAt:new Date().toISOString(),filters:{source,subject},questionIds:corpus.questions.map(q=>q.id),statistics:{terms:corpus.terms,subjects:corpus.subjects,signals:corpus.signals,duplicates:corpus.duplicates},annotations:notes,limitations:'Análise descritiva; não identifica autoria por estilo nem prevê questões. Anotações não revisadas.'};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='pesquisa-banca.json';a.click();URL.revokeObjectURL(url);setMessage('Relatório exportado. Guarde o arquivo para retomar a pesquisa.');}
 async function importReport(file:File|undefined){if(!file)return;try{const data=JSON.parse(await file.text());if(data.version!==RESEARCH_VERSION||!data.annotations||typeof data.annotations!=='object'||Array.isArray(data.annotations))throw Error();const imported:Record<string,Annotation>={};for(const [id,value] of Object.entries(data.annotations)){if(!questions.some(q=>q.id===id)||!value||typeof value!=='object')continue;const entry={...empty};for(const key of Object.keys(empty) as (keyof Annotation)[])if(typeof (value as Annotation)[key]==='string')entry[key]=(value as Annotation)[key].slice(0,20000);if(!['unknown','human','ai','hybrid'].includes(entry.authorship))entry.authorship='unknown';imported[id]=entry;}setNotes({...notes,...imported});setMessage('Anotações importadas. Revise a evidência antes de confirmar autoria.');}catch{setMessage('Arquivo inválido. Importe um relatório exportado por esta área.');}}
 return <main className="researchPage"><header><Link href="/">← Estante</Link><Link href="/estudar">Estudar com SRS</Link></header><h1>Pesquisa da banca</h1><p>Conceitos, vocabulário e construção das alternativas, com evidências rastreáveis.</p>
 <div className="researchFilters"><label>Fonte / prova<select value={source} onChange={e=>{setSource(e.target.value);setSubject('');setSelected('');}}><option value="">Todas — corpus misto</option>{sources.map(s=><option key={s}>{s}</option>)}</select></label><label>Disciplina / assunto<select value={subject} onChange={e=>{setSubject(e.target.value);setSelected('');}}><option value="">Todos os assuntos</option>{subjects.map(s=><option key={s}>{s}</option>)}</select></label><button onClick={exportReport}>Exportar pesquisa</button><label>Retomar relatório<input type="file" accept=".json,application/json" onChange={e=>void importReport(e.target.files?.[0])}/></label></div>
 <p role="status">{message}</p><p className="researchNotice">Anotações ficam apenas nesta sessão: exporte antes de fechar. Fontes e assuntos são os metadados existentes, não uma identificação validada de banca. Um corpus misto não descreve uma banca específica.</p>
 <section className="researchStats"><div><strong>{corpus.questions.length}</strong> questões distintas</div><div><strong>{corpus.duplicates}</strong> duplicatas exatas removidas</div><div><strong>{corpus.tokenCount}</strong> palavras no enunciado e alternativas</div></section>
 <div className="researchColumns"><section><h2>Vocabulário observado</h2><p>Frequência descritiva, sem teste de distintividade contra outra banca. Clique para ver o uso em contexto.</p><div className="researchTerms">{corpus.terms.slice(0,30).map(t=><button key={t.term} onClick={()=>{setQuery(t.term);setSelected('');}}>{t.term} · {t.count} ocorrências · {t.ids.length} itens · {t.perThousand.toFixed(1)}/mil</button>)}</div><h2>Linguagem e comandos</h2>{corpus.signals.map(s=><p key={s.name}>{s.name}: {s.ids.length}/{corpus.questions.length} itens</p>)}<p>Essas palavras não tornam uma alternativa errada automaticamente.</p><h2>Conceitos catalogados</h2>{corpus.subjects.slice(0,12).map(s=><p key={s.subject}>{s.subject} · {s.ids.length} itens</p>)}</section>
 <section><h2>Questões e evidências</h2><label>Buscar termo ou questão<input value={query} onChange={e=>{setQuery(e.target.value);setSelected('');}}/></label><p>{results.length} resultados</p><select aria-label="Selecionar questão" value={q?.id??''} onChange={e=>setSelected(e.target.value)}>{results.map(item=><option key={item.id} value={item.id}>{item.notebookTitle} · {item.number} · {item.subject}</option>)}</select>{!q?<p>Nenhuma questão neste recorte.</p>:<><h3>{q.label}</h3><p>{q.prompt}</p><ol type="A">{q.options.map((option,i)=><li key={i}>{option}{i===q.answer?' — gabarito registrado':''}{q.optionAnalysis?.[i]&&<p>{q.optionAnalysis[i]}</p>}</li>)}</ol><p>{q.explanation||'Sem explicação conceitual revisada.'}</p><p>Fonte registrada: {q.source}</p>{q.sourceUrl&&<a href={q.sourceUrl} target="_blank" rel="noreferrer">Conferir origem registrada</a>}{q.citations?.map(c=><p key={c.id}>{c.title} · {c.locator} · {c.verified?'referência marcada como verificada':'referência não verificada'}</p>)}<p>Sinais: {languageSignals([q.prompt,...q.options].join(' ')).map(s=>`${s.name}: ${s.matches.join(', ')}`).join(' / ')||'Nenhum sinal do manual identificado.'}</p>
 <h3>Ficha de conceito e desenho do item</h3>{([['concept','Conceito-alvo'],['definition','Definição e vocabulário técnico'],['confusion','Conceitos confundidos pelos distratores'],['task','Conhecimento exigido e evidência de domínio (ECD)'],['references','Livro, edição, página impressa/PDF e trecho de apoio'],['hypothesis','Hipótese de nova cobrança — não é previsão']] as [keyof Annotation,string][]).map(([key,label])=><label key={key}>{label}<textarea value={annotation[key]} onChange={e=>update(key,e.target.value)}/></label>)}
 <h3>Proveniência da autoria</h3><p>Autoria não identificada por padrão. Prova oficial não comprova escrita exclusivamente humana. Não estimamos porcentagem de IA nem adivinhamos o modelo.</p><label>Autoria declarada em documento<select value={annotation.authorship} onChange={e=>update('authorship',e.target.value)}><option value="unknown">Não identificada</option><option value="human">Humana — requer evidência</option><option value="ai">IA — requer evidência</option><option value="hybrid">Híbrida — requer evidência</option></select></label><label>Autor / instituição declarados<input value={annotation.author} onChange={e=>update('author',e.target.value)}/></label><label>Modelo e versão declarados (se houver)<input value={annotation.model} onChange={e=>update('model',e.target.value)}/></label><label>Evidência documental / URL / log de geração<textarea value={annotation.evidence} onChange={e=>update('evidence',e.target.value)}/></label>{annotation.authorship!=='unknown'&&!annotation.evidence.trim()&&<p className="researchNotice">Sem evidência: esta classificação é uma declaração pendente, não autoria comprovada.</p>}</> }</section></div>
 <details><summary>Protocolo científico e limites</summary><p>1. Delimitar banca, cargo, disciplina e período. 2. Deduplicar e codificar conceitos e linguagem com manual explícito. 3. Revisar uma amostra por avaliador independente e registrar divergências. 4. Reservar provas posteriores antes de ajustar hipóteses. 5. Elaborar itens pelo ECD, revisar conteúdo e distratores. 6. Com respostas reais, avaliar dificuldade e discriminação; tentativas repetidas no SRS não são amostra independente.</p><p>Esta versão implementa descrição do corpus e fichas revisáveis. Não executa validação temporal, psicometria, busca automática nos livros ou geração de inéditas. Frequência não é probabilidade de cair.</p><ul><li><a href="https://doi.org/10.1111/nhs.12048">Análise de conteúdo — Vaismoradi et al.</a></li><li><a href="https://www.ets.org/Media/Research/pdf/session1-cameto-cheng-haertel-paper-tea2012.pdf">Design centrado em evidências — ETS</a></li><li><a href="https://www.lancaster.ac.uk/fss/courses/ling/corpus/blue/l03_2.htm">Vocabulário e corpus de referência — Lancaster</a></li><li><a href="https://aclanthology.org/2024.acl-long.160/">Limites de detectores de texto gerado por IA — ACL 2024</a></li></ul></details></main>;
}
