"use client";
import Link from "next/link";
import {useEffect,useMemo,useRef,useState} from "react";
export type AdminBankQuestion={number:number;tecId:string;source:string;subject:string;prompt:string;options:string[];answer:number};
const officialAnswers="A B E B C E E B D E C A E B B B E D B C E E E D D C E D E B C D C B E E D B A C A A E C A B A A A C A D C A D E B E E A B E D B A C D C C D E D E B B E D B C B A D B C A C B D E C D C B B A C A A B B A C B C D C B".split(" ").map(letter=>letter.charCodeAt(0)-65);
const vocabulary=[["EXCETO / INCORRETA","Invertem a busca: marque a única alternativa que não pertence à regra."],["TODO / SEMPRE / NUNCA","Termos absolutos: uma única exceção derruba a proposição."],["APENAS / SOMENTE","Restringem o alcance. Verifique se existem outras hipóteses."],["DEVERÁ / PODERÁ","Dever indica obrigação; poder indica faculdade."],["E / BEM COMO","Criam resposta composta: todos os elementos precisam ser verdadeiros."],["COMPETE / INCUMBE","A ação pode existir, mas pertencer a outro agente."],["ESTRITAMENTE / ÚNICA","Procure exceção, inversão de fases ou procedimento alternativo."],["CORRESPONDE","Exige identidade precisa; proximidade semântica não basta."]];
const cards=[
  ["Como resolver um comando com EXCETO?","Procure a única opção que não pertence ao conjunto.","Comando"],["Por que desconfiar de “sempre”?","Basta uma exceção válida para derrubar uma afirmação universal.","Predição"],["Empenho x liquidação","Empenho cria a obrigação; liquidação verifica o direito do credor.","Orçamento"],["Pregoeiro x autoridade competente","O pregoeiro conduz; a autoridade competente homologa.","Licitações"],["Macroambiente x microambiente","Macro: forças gerais. Micro: clientes, fornecedores, concorrentes e entrantes.","Organização"],["Planejamento tático","Médio prazo, alcance departamental e desdobramento da estratégia.","Planejamento"],["Trio primário da logística","Transportes, manutenção de estoques e processamento de pedidos.","Materiais"],["TIR x TMA","O investimento é aceitável quando a TIR supera a TMA.","Finanças"],["Comissão de Ética: penalidade","Censura fundamentada em parecer, não demissão ou suspensão.","Ética"],["Alternativa ligada por “e”","Um único elemento falso invalida a opção inteira.","Linguagem"],["Sequência V/F: onde começar?","Na assertiva mais distintiva; depois elimine sequências incompatíveis.","Método"],["Alternativa tecnicamente fluente","Confira categoria, finalidade, agente, prazo e exceção.","Método"]
] as const;
const tidy=(v:string)=>v.replace(/30\/08\/2026, 21:04[^\n]*/g,"").replace(/https:\/\/www\.tecconcursos\.com\.br\/questoes\/cadernos\/[^\s]+/g,"").replace(/\b\d+\/33\b/g,"").replace(/\s+/g," ").trim();
const repair=(value:string)=>{const joined:Record<string,string>={"queos":"que os","queas":"que as","queo":"que o","quea":"que a","paraos":"para os","paraas":"para as","paraa":"para a","comoas":"como as","comoos":"como os","entreas":"entre as","entreos":"entre os","sobreas":"sobre as","sobreos":"sobre os","namovimentação":"na movimentação","nolugar":"no lugar","noinstante":"no instante","daorganização":"da organização","doEstado":"do Estado","dasorganizações":"das organizações","doservidor":"do servidor"};let result=value.replace(/(?:\d+\)\s*){2,}/g,"").replace(/Página \d+ de \d+[^.]*ADMINISTRADOR/gi,"").replace(/CONCURSO PÚBLICO[^.]*IFMT/gi,"").replace(/([,.;:])(?=[A-ZÁÉÍÓÚ])/g,"$1 ");for(const[from,to]of Object.entries(joined))result=result.replace(new RegExp(`\\b${from}\\b`,"gi"),to);return tidy(result)};
export function PromptBlocks({text}:{text:string}){const structured=repair(text).replace(/\s+(?=(?:I|II|III|IV|V|VI|VII)\s*[-.])/g,"\n").replace(/\s*(?=\(\s*\))/g,"\n").replace(/\s+(?=(?:Assinale|Marque|Identifique|Está correto|Estão corret|Agora, assinale|Em seguida, assinale)\b)/g,"\n");const blocks=structured.split("\n").map(item=>item.trim()).filter(Boolean);return <div className="questionPrompt">{blocks.map((block,index)=>{const item=/^(?:I|II|III|IV|V|VI|VII)\s*[-.]|^\(\s*\)/.test(block);const command=/^(?:Assinale|Marque|Identifique|Está correto|Estão corret|Agora, assinale|Em seguida, assinale)/.test(block);return <p key={`${index}-${block.slice(0,20)}`} className={item?"assertion":command?"command":"context"}>{block}</p>})}</div>}
export function parseAdminQuestions(text:string):AdminBankQuestion[]{const marker=/www\.tecconcursos\.com\.br\/questoes\/(\d+)/g;const matches=[...text.matchAll(marker)];return matches.map((m,i)=>{const raw=text.slice((m.index??0)+m[0].length,i+1<matches.length?(matches[i+1].index??text.length):text.length);const lines=raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const si=lines.findIndex(x=>x.startsWith("COCP IFMT"));const source=si>=0?lines[si]:"COCP IFMT";const subject=si>=0?lines[si+1]??"Assunto não identificado":"Assunto não identificado";let body=si>=0?lines.slice(si+2).join(" "):raw;body=body.replace(/\d+\)\s*$/g,"");const om=[...body.matchAll(/([a-e])\)\s*/gi)].slice(-5);const prompt=repair(body.slice(0,om[0]?.index??body.length));const options=om.map((item,j)=>repair(body.slice((item.index??0)+item[0].length,j+1<om.length?(om[j+1].index??body.length):body.length).replace(/\d+\)\s*$/g,""))).filter(Boolean);return {number:i+1,tecId:m[1],source,subject:tidy(subject),prompt,options,answer:officialAnswers[i]}})}
export function signals(q:AdminBankQuestion){const t=`${q.prompt} ${q.options.join(" ")}`.toLowerCase();const s:string[]=[];if(/exceto|incorreta|não corresponde|não são/.test(t))s.push("Comando negativo: procure a única opção que foge da regra.");if(/\b(todo|toda|todos|todas|sempre|somente|apenas|nunca|estritamente|exclusivamente)\b/.test(t))s.push("Termo absoluto ou restritivo: teste se existe exceção.");if(/I\.|II\.|III\.|\(\s*\)/.test(q.prompt))s.push("Questão combinatória: resolva primeiro a assertiva mais segura.");if(/lei|decreto|art\.|comissão|autoridade|pregoeiro/.test(t))s.push("Confira agente, competência, prazo e força do verbo legal.");if(q.options.some(x=>x.includes(" e ")))s.push("Resposta composta: um elemento errado invalida a alternativa.");return (s.length?s:["Compare o núcleo técnico; fluência textual não comprova correção."]).slice(0,3)}
const decisivePatterns=[
 {pattern:/\b(todo|toda|todos|todas|sempre|nunca|exclusivamente|unicamente)\b/i,note:"é absoluto; basta uma exceção válida para eliminar a afirmação."},
 {pattern:/\b(apenas|somente|estritamente|única|único)\b/i,note:"restringe o alcance; verifique se a regra admite outras hipóteses."},
 {pattern:/\b(deverá|deve|obrigatoriamente)\b/i,note:"indica obrigação; confirme se a norma realmente impõe essa conduta."},
 {pattern:/\b(poderá|pode|facultativamente)\b/i,note:"indica faculdade ou possibilidade, não obrigação."},
 {pattern:/\b(exceto|incorreta|não|jamais)\b/i,note:"inverte ou nega a proposição; releia o comando antes de julgar."},
 {pattern:/\b(compete|incumbe|atribuição|responsabilidade)\b/i,note:"define o agente competente; uma troca de autoridade costuma formar o distrator."},
 {pattern:/\b(antes|depois|previamente|posteriormente|imediatamente)\b/i,note:"marca ordem ou prazo; confira a fase correta do procedimento."},
] as const;
export function decisiveTerms(q:AdminBankQuestion){return q.options.flatMap((option,index)=>{const hit=decisivePatterns.find(({pattern})=>pattern.exec(option));if(!hit)return[];const term=option.match(hit.pattern)?.[0]??"";return[{option:index,term,note:hit.note}]})}
function optionReview(q:AdminBankQuestion,index:number){if(index===q.answer)return"corresponde ao gabarito oficial. Confirme no enunciado o conceito, agente, finalidade e alcance que tornam a proposição precisa.";const decisive=decisiveTerms(q).find(item=>item.option===index);return decisive?`é um distrator. O termo “${decisive.term}” merece teste: ${decisive.note}`:"é um distrator. Compare seu núcleo conceitual, agente, finalidade, prazo ou alcance com a alternativa correta."}
export function route(subject:string){if(/Ética|Direito Administrativo|AFO|Financeiro|Contabilidade|Licita/.test(subject))return "/administracao-publica";if(/Materiais|Logística|Pessoas|Desempenho|Treinamento|Qualidade de Vida/.test(subject))return "/administracao-pessoas-logistica";return "/administracao-gestao"}
function speaker(q:AdminBankQuestion){const text=`${q.subject} ${q.prompt}`.toLowerCase();if(/logíst|materiais|cadeia|patrimonial/.test(text))return{name:'Ronald H. Ballou',role:'Logística e materiais',initials:'RB'};if(/planejamento|organiza|pessoas|liderança/.test(text))return{name:'Idalberto Chiavenato',role:'Administração e gestão',initials:'IC'};if(/orçamento|licita|ética|lei|decreto|constitui|administrativo/.test(text))return{name:'Fonte normativa',role:'Legislação e setor público',initials:'BR'};if(/finan|projeto|risco/.test(text))return{name:'Referência do tema',role:'Finanças e projetos',initials:'FT'};return{name:'Caderno IFMT',role:q.subject,initials:'IF'};}
export default function CompleteAdminBank(){
 const[questions,setQuestions]=useState<AdminBankQuestion[]>([]),[query,setQuery]=useState(""),[subject,setSubject]=useState("Todos os assuntos"),[active,setActive]=useState(0),[selected,setSelected]=useState<number|null>(null),[revealed,setRevealed]=useState(false),[flipped,setFlipped]=useState<number[]>([]),[error,setError]=useState(""),[petMode,setPetMode]=useState(false),[listening,setListening]=useState(false),[petMessage,setPetMessage]=useState("Ative o modo pet para ouvir a questão e responder falando A, B, C, D ou E.");
 const recognition=useRef<{start:()=>void;stop:()=>void;onresult:null|((event:{results:ArrayLike<ArrayLike<{transcript:string}>>})=>void);onend:null|(()=>void);onerror:null|(()=>void)}|null>(null);
 useEffect(()=>{fetch("/data/administrador-ifmt-107.txt").then(r=>{if(!r.ok)throw new Error();return r.text()}).then(t=>setQuestions(parseAdminQuestions(t))).catch(()=>setError("Não foi possível carregar o banco integral."))},[]);
 const subjects=useMemo(()=>["Todos os assuntos",...Array.from(new Set(questions.map(q=>q.subject))).sort((a,b)=>a.localeCompare(b,"pt-BR"))],[questions]);
 const filtered=useMemo(()=>questions.filter(q=>(subject==="Todos os assuntos"||q.subject===subject)&&`${q.prompt} ${q.subject}`.toLowerCase().includes(query.toLowerCase())),[questions,query,subject]);const q=filtered[active];const progress=filtered.length?Math.round(((active+1)/filtered.length)*100):0;
 const reset=(n=0)=>{setActive(n);setSelected(null);setRevealed(false)},next=()=>{reset((active+1)%filtered.length);requestAnimationFrame(()=>document.getElementById("questoes")?.scrollIntoView({behavior:"smooth",block:"start"}))},random=()=>filtered.length&&reset(Math.floor(Math.random()*filtered.length));
 const speak=(text:string)=>{if(typeof window==='undefined'||!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='pt-BR';utterance.rate=.94;window.speechSynthesis.speak(utterance)};
 const speakQuestion=()=>{if(!q)return;const text=`Questão ${q.number}. ${q.prompt}. Alternativa A: ${q.options[0]}. Alternativa B: ${q.options[1]}. Alternativa C: ${q.options[2]}. Alternativa D: ${q.options[3]}. Alternativa E: ${q.options[4]}.`;speak(text);setPetMessage('Estou lendo. Depois diga apenas a letra da alternativa.');};
 const answerFromSpeech=(transcript:string)=>{const value=transcript.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');const words=[['a','á','letra a','alternativa a'],['b','be','bê','letra b','alternativa b'],['c','ce','cê','letra c','alternativa c'],['d','de','dê','letra d','alternativa d'],['e','é','letra e','alternativa e']];for(let i=0;i<words.length;i++)if(words[i].some(word=>new RegExp(`(^|\\s)${word.replace(/[.*+?^${}()|[\\]\\\\]/g,'\\\\$&')}(?=\\s|$)`).test(value))){setSelected(i);setRevealed(true);setPetMessage(`Você respondeu ${String.fromCharCode(65+i)}. Confira a análise e diga “próxima” quando quiser continuar.`);speak(`${String.fromCharCode(65+i)} selecionada. ${i===q.answer?'Você acertou.':'Vamos conferir a explicação.'}`);return true;}return false;};
 const listen=()=>{if(typeof window==='undefined')return;const Recognition=(window as Window & {SpeechRecognition?:new()=>typeof recognition.current;webkitSpeechRecognition?:new()=>typeof recognition.current}).SpeechRecognition||(window as Window & {webkitSpeechRecognition?:new()=>typeof recognition.current}).webkitSpeechRecognition;if(!Recognition){setPetMessage('Seu navegador não oferece reconhecimento de voz. Use os botões das alternativas.');return;}const current=new (Recognition as new()=>NonNullable<typeof recognition.current>)();current.onresult=(event)=>{setListening(false);const transcript=Array.from(event.results as ArrayLike<ArrayLike<{transcript:string}>>).map(item=>item[0].transcript).join(' ');if(!answerFromSpeech(transcript))setPetMessage(`Não identifiquei uma letra em “${transcript}”. Diga A, B, C, D ou E.`);};current.onend=()=>setListening(false);current.onerror=()=>{setListening(false);setPetMessage('Não consegui ouvir. Verifique a permissão do microfone e tente novamente.');};recognition.current=current;setListening(true);setPetMessage('Estou ouvindo… diga A, B, C, D ou E.');current.start();};
 useEffect(()=>{if(petMode&&q&&!revealed)speakQuestion();return()=>{if(typeof window!=='undefined'&&'speechSynthesis' in window)window.speechSynthesis.cancel();recognition.current?.stop();};},[petMode,active,q?.tecId]);
 return <main className="completeBank examNotebook adminStrategy">
  <header className="completeTop"><Link href="/" className="brand"><span>20D</span>Cadernos de Estudo</Link><nav><a href="#vocabulario">Vocabulário</a><a href="#questoes">Estudo guiado</a><a href="#cards">Cards</a><button onClick={random}>Sortear questão</button><button className={petMode?"petOn":""} onClick={()=>{setPetMode(v=>!v);setPetMessage(petMode?'Modo pet pausado.':'Modo pet ativo: vou ler e ouvir suas respostas.')}}>🌱 {petMode?'Pausar pet':'Modo pet'}</button></nav></header>
  <section className="catalogHero"><div><span>BANCO INTEGRAL · IFMT</span><h1>Administração<br/><em>banco completo.</em></h1><p>As 107 questões do arquivo transformadas em uma experiência de leitura, julgamento e justificativa.</p></div><div className="catalogStats"><div><b>{questions.length||"…"}</b><small>questões catalogadas</small></div><div><b>{Math.max(0,subjects.length-1)||"…"}</b><small>assuntos distintos</small></div><div><b>12</b><small>cards de distinção</small></div></div></section>
  <section className="bankVocabulary" id="vocabulario"><div><span>VOCABULÁRIO DA BANCA</span><h2>Palavras que mudam<br/><em>o valor da alternativa.</em></h2><p>Antes do conteúdo, identifique a força lógica e normativa das palavras.</p></div><div className="vocabularyGrid">{vocabulary.map(([w,n])=><article key={w}><strong>{w}</strong><p>{n}</p></article>)}</div></section>
  <section className="guidedHeader"><span>ESTUDO GUIADO</span><h2>Leia. Julgue.<br/><em>Justifique.</em></h2><p>A análise separa o conteúdo técnico das pistas linguísticas usadas pela banca.</p></section>
  <section className="guidedControls"><label><span>BUSCAR</span><input value={query} onChange={e=>{setQuery(e.target.value);reset()}} placeholder="Conceito, lei ou palavra…"/></label><label><span>ASSUNTO</span><select value={subject} onChange={e=>{setSubject(e.target.value);reset()}}>{subjects.map(x=><option key={x}>{x}</option>)}</select></label><div><b>{filtered.length}</b><span>questões no recorte</span></div></section>
  {error&&<p className="catalogError">{error}</p>}{!error&&!questions.length&&<p className="catalogLoading">Organizando o caderno…</p>}
  {q&&<section className="guidedStudy" id="questoes">
   <aside><span>PROGRESSO</span><h3>{active+1} de {filtered.length}</h3><div className="guidedProgress"><i style={{width:`${progress}%`}}/></div><small>{progress}% concluído</small><div className="guidedNav">{filtered.map((item,i)=><button key={item.tecId} className={active===i?"active":""} onClick={()=>reset(i)}>{i+1}</button>)}</div><button className="randomQuestion" onClick={random}>↻ Sortear deste assunto</button></aside>
   <article className="guidedQuestion"><div className="catalogMeta"><span>QUESTÃO {String(q.number).padStart(3,"0")}</span><a href={`https://www.tecconcursos.com.br/questoes/${q.tecId}`} target="_blank" rel="noreferrer">FONTE ORIGINAL ↗</a></div>{petMode&&<div className={`petCompanion ${listening?'petListening':''}`} role="status" aria-live="polite"><div className="petAvatar" aria-hidden="true">🌱</div><div><strong>Companheiro de estudo</strong><p>{petMessage}</p></div><div className="petActions"><button onClick={speakQuestion}>🔊 Ouvir</button><button onClick={listen} disabled={listening||revealed}>🎙️ {listening?'Ouvindo…':'Responder por voz'}</button></div></div>}<p className="catalogSubject">ASSUNTO · {q.subject}</p><small>{q.source}</small><PromptBlocks text={q.prompt}/><div className="guidedOptions">{q.options.map((o,i)=><button key={o} className={`${selected===i?"selected":""} ${revealed&&q.answer===i?"correct":revealed&&selected===i&&q.answer!==undefined?"wrong":""}`} onClick={()=>!revealed&&setSelected(i)}><b>{String.fromCharCode(65+i)}</b><span>{o}</span></button>)}</div><div className="guidedActions"><button disabled={selected===null} onClick={()=>setRevealed(v=>!v)}>{revealed?"Ocultar correção":"Corrigir e ver gabarito"}</button><button onClick={next}>Próxima questão →</button></div>
    {revealed&&<div className="guidedAnalysis"><strong>{q.answer!==undefined?`GABARITO OFICIAL: ${String.fromCharCode(65+q.answer)}`:"GABARITO OFICIAL AINDA NÃO VALIDADO"}</strong>{q.answer!==undefined&&<p className={selected===q.answer?"answerHit":"answerMiss"}>{selected===q.answer?"Você acertou.":`Sua resposta: ${String.fromCharCode(65+(selected??0))}. Revise a distinção abaixo.`}</p>}
     <div><h4>ANÁLISE DAS ALTERNATIVAS</h4><ul className="optionReview">{q.options.map((option,index)=><li key={option} className={index===q.answer?"isAnswer":""}><b>{String.fromCharCode(65+index)} — {index===q.answer?"CORRETA":"DISTRATOR"}:</b> {optionReview(q,index)}</li>)}</ul></div>
     <div><h4>LINGUÍSTICO + PREDIÇÃO</h4><ul>{decisiveTerms(q).length?decisiveTerms(q).map(item=><li key={`${item.option}-${item.term}`}><b>Alternativa {String.fromCharCode(65+item.option)} · “{item.term}”:</b> {item.note}</li>):signals(q).map(s=><li key={s}>{s}</li>)}</ul></div>
     <div><h4>CONCEITUAL</h4><p>{q.answer!==undefined?"A resposta foi conferida com o gabarito definitivo da prova oficial. Use a análise acima para confrontar cada distrator com a alternativa correta.":"Esta questão integra o banco temático, mas sua resposta oficial ainda não foi comprovada. Consulte a fonte original; não exibimos um palpite como gabarito da banca."}</p></div><Link href={`${route(q.subject)}?questao=${q.number}#banco-do-caderno`}>Revisar esta questão no caderno comentado →</Link>
    </div>}
   </article>
  </section>}
  <section className="activeMemory" id="cards"><header><div><span>MEMORIZAÇÃO ATIVA</span><h2>Conceito curto.<br/><em>Distinção precisa.</em></h2></div><p>Formule a resposta antes de virar cada card.</p></header><div className="memoryGrid">{cards.map((c,i)=><button key={c[0]} className={flipped.includes(i)?"flipped":""} onClick={()=>setFlipped(v=>v.includes(i)?v.filter(x=>x!==i):[...v,i])}><small>{c[2]} · {String(i+1).padStart(2,"0")}</small><strong>{flipped.includes(i)?c[1]:c[0]}</strong><span>{flipped.includes(i)?"↶ ver pergunta":"virar card ↗"}</span></button>)}</div></section>
 </main>
}
