export default function FeedbackEvidence() {
  return <section>
    <h3>Por que explicar o conceito e cada alternativa?</h3>
    <p><strong>Feedback explicativo:</strong> dizer apenas a letra certa não mostra como chegar à resposta. Nosso padrão editorial é definir o conceito, aplicá-lo ao trecho exato, explicar a condição atendida ou violada em cada opção e acrescentar um exemplo contrastante quando ele ajudar. A explicação aparece depois da tentativa; os detalhes podem ser abertos por partes.</p>
    <p><a href="https://doi.org/10.1007/s40037-020-00606-z" target="_blank" rel="noreferrer">Ryan et al. (2020)</a> compararam feedback de certo/errado com explicações por alternativa e explicações conceituais em questões médicas de múltipla escolha. Os dois formatos elaborados favoreceram questões novas em testes imediatos e após uma semana; não houve diferença significativa entre eles. É evidência próxima desta proposta, mas vem de um contexto e de uma amostra específicos, não de concursos do IFMT.</p>
    <p><a href="https://doi.org/10.1037/a0031026" target="_blank" rel="noreferrer">Butler, Godbole e Marsh (2013)</a> encontraram vantagem de explicações sobre o mero gabarito em novas perguntas de inferência após dois dias, mas não nas perguntas repetidas. Os experimentos usaram respostas curtas, não a análise das cinco opções de múltipla escolha.</p>
    <p><strong>Você também precisa explicar:</strong> ler o comentário pronto não equivale a produzir uma autoexplicação. A pergunta “qual detalhe decide a resposta?” solicita uma relação conceitual com suas palavras. A <a href="https://doi.org/10.1007/s10648-018-9434-x" target="_blank" rel="noreferrer">meta-análise de Bisra et al. (2018)</a> apoia essa prática em diferentes tarefas.</p>
    <p><a href="https://doi.org/10.3102/0034654307313795" target="_blank" rel="noreferrer">Shute (2008)</a> recomenda feedback específico e centrado na tarefa, em partes manejáveis. Mais texto não significa, por si só, melhor aprendizagem: cada comentário precisa ensinar uma distinção real, sem repetir “está errada porque não é o gabarito”.</p>
    <p><strong>Limites e integridade:</strong> combinar conceito, aplicação, contraste e autoexplicação é uma decisão de produto informada por essas pesquisas; a sequência completa não foi validada neste aplicativo. As evidências não garantem aprovação. Fontes de origem, gabarito e conceito são identificadas separadamente. Quando não conseguimos sustentar uma classificação, mostramos a dúvida; não inventamos razões para concordar com o gabarito.</p>
  </section>;
}
