import {ExamCard,ExamQuestion,NotebookConfig} from "./components/ExamNotebook";

export const source="IFMT · Administrador · Edital 133/2023";
export const bankProfile=[
  "EXCETO / INCORRETA: inverta o comando antes de ler as opções.",
  "Apenas, somente, estritamente e sempre tornam a afirmação mais vulnerável.",
  "Listas ligadas por “e” exigem que todos os elementos estejam corretos.",
  "Termos próximos não são equivalentes: empenho ≠ liquidação ≠ pagamento.",
  "Nas sequências, resolva primeiro o item mais distintivo e elimine combinações.",
  "Uma opção pode soar técnica e ainda estar errada por trocar competência, fase ou finalidade."
];
export const statementMode="Texto essencial da questão preservado; casos longos foram condensados sem alterar o comando nem as alternativas.";

export const questions:ExamQuestion[]=[
{examId:"41",source,subject:"Planejamento estratégico · níveis",prompt:"O planejamento projetado a médio prazo, que abrange cada unidade da organização e desdobra objetivos institucionais em objetivos departamentais, corresponde a qual tipo?",options:["Tático.","Por processo.","Estratégico.","Por objetivos.","Operacional."],answer:0,explanation:"O nível tático traduz a estratégia para áreas ou departamentos, em horizonte intermediário. O estratégico é institucional e de longo prazo; o operacional detalha rotinas de curto prazo.",languageNote:"“Médio prazo”, “cada unidade” e “departamentais” convergem para tático. Distratores trocam nível, horizonte e abrangência.",xray:"assunto + três marcadores concordantes → tático"},
{examId:"42",source,subject:"Liderança · estilos",prompt:"Um líder toma decisões arbitrárias, mantém controle rígido, faz exigências duras, demonstra pouca preocupação com o bem-estar da equipe e se concentra em resultados. Seu estilo é:",options:["Democrático.","Liberal.","Autocrático.","Carismático.","Técnico."],answer:2,explanation:"Centralização da decisão, controle rígido e baixa participação dos subordinados caracterizam liderança autocrática.",languageNote:"A banca acumula pistas semânticas negativas — “arbitrárias”, “rígido”, “intimidação” — para formar um campo lexical de centralização.",xray:"campo lexical do controle → autocrático"},
{examId:"43",source,subject:"Equipes · alta performance",prompt:"Segundo Maximiano, são características de grupos de alta performance, EXCETO:",options:["Coesão: interesse na continuidade do grupo.","Envolvimento psicológico: motivação oferecida pela tarefa.","Confiança e controle: sintonia e ações corretivas e coercitivas constantes.","Compreensão das interdependências: entender que o grupo depende de todos.","Autorregulação: capacidade de cuidar de si próprio."],answer:2,explanation:"Alta performance envolve confiança e autorregulação, não controle coercitivo constante. A alternativa C combina um rótulo positivo com uma definição incompatível.",languageNote:"“EXCETO” pede a intrusa. Observe a ruptura vocabular: “coercitivas constantes” destoa de coesão, confiança e autorregulação.",xray:"rótulo plausível + definição tóxica = distrator"},
{examId:"44",source,subject:"Organização · ambiente",prompt:"Classifique: distribuição de renda; legislação governamental; ameaça de novos entrantes; clientes. Use I para macroambiente e II para microambiente.",options:["I, I, I, II.","I, II, II, II.","II, I, II, I.","I, II, I, II.","I, I, II, II."],answer:4,explanation:"Forças demográficas e político-legais pertencem ao ambiente geral; novos entrantes e clientes atuam no ambiente setorial.",languageNote:"“Governamental/demográfica” aponta para o contexto amplo; “entrantes/clientes” nomeia atores próximos. Resolva os polos antes de comparar a sequência.",xray:"força geral, força geral, ator setorial, ator setorial"},
{examId:"45",source,subject:"Teorias administrativas · autores",prompt:"Associe: Frederick Taylor, Henry Ford e Henri Fayol às contribuições: organização do processo produtivo; organização da empresa e do papel do dirigente; eficiência do trabalho operacional.",options:["I, II, III.","III, II, I.","I, III, II.","II, I, III.","II, III, I."],answer:4,explanation:"Ford liga-se à organização do processo produtivo; Fayol à empresa e às funções do dirigente; Taylor à eficiência do trabalho operacional.",languageNote:"Os núcleos “processo produtivo”, “empresa/dirigente” e “trabalho operacional” funcionam como âncoras vocabulares para Ford, Fayol e Taylor.",xray:"Ford-produção · Fayol-direção · Taylor-tarefa"},
{examId:"46",source,subject:"Logística · atividades primárias e apoio",prompt:"Classifique como I (primária) ou II (apoio): obtenção; transportes; armazenagem; processamento de pedidos; manutenção de estoques; programação de produtos; informação; embalagem; manuseio.",options:["II, I, II, I, I, II, II, II, II.","II, I, II, I, I, I, I, II, II.","I, I, I, II, I, II, II, II, I.","I, I, I, II, II, II, II, I, II.","I, I, II, I, II, I, I, II, I."],answer:0,explanation:"Em Ballou, transportes, manutenção de estoques e processamento de pedidos são primárias; as demais listadas apoiam essas atividades.",languageNote:"A banca explora listas longas. Fixe primeiro o trio primário; qualquer alternativa que altere um desses três cai sem classificar tudo.",xray:"trio-chave: transporte + estoque + pedidos"},
{examId:"47",source,subject:"Logística · curva ABC e custos",prompt:"Julgue: I. a curva ABC deriva de Pareto; II. peso, volume, valor, perecibilidade, inflamabilidade, cor, design e substitutibilidade influenciam a distribuição; III. custo de oportunidade do capital integra a manutenção de estoques.",options:["V, V, V.","V, F, V.","V, F, F.","F, V, V.","F, V, F."],answer:1,explanation:"I e III são verdadeiros. Em II, cor e design não integram a lista logística de características determinantes apresentada por Ballou.",languageNote:"Listas são vulneráveis ao “elemento intruso”. Dois termos cotidianos e visuais — “cor” e “design” — ampliam indevidamente a enumeração técnica.",xray:"enumeração quase correta + dois intrusos"},
{examId:"48",source,subject:"Gestão de pessoas · desenho de cargos",prompt:"São aspectos do modelo clássico de desenho de cargos, EXCETO:",options:["Pessoa como apêndice da máquina.","Fragmentação em subtarefa simples e repetitiva.","Ênfase na eficiência, método e regras.","Identidade com a tarefa e realização de trabalho inteiro ou global.","Permanência e estabilidade do processo produtivo."],answer:3,explanation:"Identidade com a tarefa e trabalho integral pertencem a desenhos enriquecidos, não ao modelo clássico fragmentado.",languageNote:"“Trabalho inteiro ou global” contradiz diretamente “fragmentação”. Em questões de exceção, procure a antonímia interna entre alternativas.",xray:"fragmentação × identidade global"},
{examId:"49",source,subject:"Gestão de pessoas · avaliação de desempenho",prompt:"Associe as definições: formulário de dupla entrada; blocos de frases; relação quantitativa de fatores; desempenhos extremos; entrevista especialista-gerente.",options:["Escalas gráficas; listas; escolha forçada; pesquisa de campo; incidentes críticos.","Escolha forçada; incidentes; listas; pesquisa; escalas.","Escalas gráficas; escolha forçada; listas de verificação; incidentes críticos; pesquisa de campo.","Listas; escolha forçada; escalas; incidentes; pesquisa.","Pesquisa; escalas; incidentes; escolha forçada; listas."],answer:2,explanation:"Dupla entrada = escalas gráficas; blocos = escolha forçada; relação de fatores = lista; extremos = incidentes críticos; entrevista = pesquisa de campo.",languageNote:"Cada definição contém uma palavra-imagem: “grade”, “escolher”, “lista”, “extremos”, “entrevista”. Converta a descrição em um rótulo curto.",xray:"imagem verbal → nome do método"},
{examId:"50",source,subject:"Gestão de pessoas · desenvolvimento",prompt:"São métodos utilizados para o desenvolvimento de pessoas, EXCETO:",options:["Jogos de empresa.","Posições de assessoria.","Aconselhamento de funcionários.","Estudo de casos.","Avaliação do retorno do investimento (ROI)."],answer:4,explanation:"ROI avalia resultados financeiros de um investimento; não é método de desenvolvimento de pessoas. Os demais promovem aprendizagem ou experiência.",languageNote:"O distrator muda de categoria: “avaliação” mede resultado, enquanto jogos, assessoria, aconselhamento e casos descrevem experiências de aprendizagem.",xray:"método de aprender × métrica de retorno"},
{examId:"51",source,subject:"Finanças · análise de investimentos",prompt:"Duas propostas têm TIR de 15% e 18%, ambas acima da TMA de 13%, no mesmo horizonte. A segunda possui a maior TIR. Qual decisão é sustentada pelos dados?",options:["Descartar ambas porque o payback é inferior a 10 anos.","Descartar ambas porque o VPL é negativo.","Escolher a empresa 1 porque a empresa 2 é inviável.","Escolher a empresa 1 porque sua TIR é mais próxima da TMA.","Escolher a empresa 2 porque sua TIR supera a da empresa 1 e a TMA."],answer:4,explanation:"Com o mesmo horizonte e TIR acima da TMA, ambas são viáveis; a empresa 2 oferece maior retorno percentual segundo o indicador disponível.",languageNote:"“Mais próxima da TMA” parece prudente, mas inverte a lógica: sendo a TMA um piso, maior distância para cima é melhor. “VPL negativo” não decorre dos dados.",xray:"TIR > TMA = viável; maior TIR = preferência"},
{examId:"52",source,subject:"Licitações · pregão",prompt:"Segundo o Decreto 3.555/2000, são atribuições do pregoeiro, EXCETO:",options:["Conduzir lances e escolher a proposta ou lance de menor preço.","Elaborar a ata.","Conduzir a equipe de apoio.","Receber, examinar e decidir recursos.","Homologar o resultado e promover a celebração do contrato."],answer:4,explanation:"Homologação e celebração contratual competem à autoridade competente, não ao pregoeiro. O pregoeiro conduz a sessão e seus atos instrutórios.",languageNote:"A banca troca o agente. Verbos de condução cabem ao pregoeiro; “homologar” indica controle final da autoridade superior.",xray:"verbo correto + sujeito errado"},
{examId:"53",source,subject:"Licitações · Lei 14.133/2021",prompt:"Julgue: I. o RDC é modalidade da Lei 14.133; II. as fases sempre seguem uma única sequência; III. menor preço, maior desconto e melhor técnica ou conteúdo artístico são critérios de julgamento.",options:["I, II e III.","I e II.","II e III.","III.","Nenhum item."],answer:3,explanation:"Somente III está correto. RDC não é modalidade da nova lei, e a habilitação pode anteceder propostas/julgamento mediante ato motivado e previsão no edital.",languageNote:"Em I ocorre troca de instituto por modalidade. Em II, “todo”, “estritamente” e “única” criam uma regra absoluta incompatível com a exceção legal.",xray:"absolutos denunciam a exceção normativa"},
{examId:"54",source,subject:"Ética · Decreto 1.171/1994",prompt:"Sobre o Código de Ética do servidor público federal, marque a alternativa INCORRETA:",options:["É vedado usar cargo e influências para obter favorecimento.","A função pública separa-se da vida privada; a conduta privada não afeta o conceito funcional.","Cortesia, urbanidade, atenção e ausência de preconceito são deveres.","A Comissão de Ética pode aplicar censura em parecer fundamentado.","É vedado apresentar-se embriagado no serviço ou fora dele habitualmente."],answer:1,explanation:"A função pública integra-se à vida particular; fatos da vida privada podem acrescer ou diminuir o conceito funcional. A alternativa B inverte o texto do decreto.",languageNote:"A banca conserva o vocabulário legal e altera uma relação: “integra-se” vira “separa-se”, e “poderão” vira “não”. Pequenas negações mudam toda a norma.",xray:"paráfrase legal com inversão semântica"},
{examId:"55",source,subject:"Ética · Sistema de Gestão",prompt:"Julgue: I. CEP e comissões de ética integram o sistema; II. o trabalho nas comissões é relevante e prioritário; III. o investigado pode conhecer imputação, acusação e autos mesmo antes de notificação.",options:["Todos os itens.","Apenas II.","Somente I e II.","Somente II e III.","Apenas III."],answer:0,explanation:"Os três itens reproduzem garantias e regras do Decreto 6.029/2007.",languageNote:"“Mesmo que ainda” introduz ressalva, não contradição. A banca testa se o candidato rejeita uma garantia por ela parecer ampla.",xray:"literalidade normativa + ressalva expressa"},
{examId:"58",source,subject:"Informática · Excel",prompt:"Associe: formatação condicional; tabela dinâmica; CONT.SE; PROCV às definições realçar por critério, resumir dados, contar por critério e buscar em coluna.",options:["I, II, III, IV.","I, IV, II, III.","IV, I, III, II.","IV, I, II, III.","I, III, IV, II."],answer:2,explanation:"Realçar = IV; resumir = I; contar = III; buscar = II. A sequência é IV, I, III, II.",languageNote:"Os próprios verbos fazem a associação: realça-formatação, resumo-tabela dinâmica, totaliza-CONT.SE, busca-PROCV.",xray:"verbo funcional → recurso"},
{examId:"59",source,subject:"Informática · segurança",prompt:"Julgue: I. firewall controla tráfego entre redes; II. impressão digital, voz, íris e rosto são biometria; III. trancas em salas de TI também são segurança da informação.",options:["Apenas I.","Somente I e II.","Apenas II.","Somente II e III.","Todos os itens."],answer:4,explanation:"Segurança da informação inclui controles lógicos, biométricos e físicos; as três proposições estão corretas.",languageNote:"O erro provável é restringir “informação” ao digital. A palavra “também” amplia corretamente o domínio para segurança física.",xray:"conceito amplo: lógico + humano + físico"},
{examId:"60",source,subject:"Orçamento · execução da despesa",prompt:"Associe as definições: cria obrigação de pagamento; verifica o direito do credor; determina que a despesa seja paga; documento com credor, valor e dedução da dotação.",options:["Empenho; liquidação; nota; ordem.","Empenho; liquidação; ordem; nota.","Liquidação; empenho; ordem; nota.","Liquidação; ordem; empenho; nota.","Liquidação; empenho; nota; ordem."],answer:1,explanation:"Empenho cria a obrigação; liquidação verifica o direito; ordem de pagamento determina o pagamento; nota de empenho materializa os dados do empenho.",languageNote:"A banca diferencia ato, verificação, despacho e documento. O substantivo nuclear da definição impede trocar etapas consecutivas.",xray:"cria → verifica → ordena → documenta"}
];

export const cards:ExamCard[]=[
{front:"Planejamento tático",back:"Médio prazo, alcance departamental e desdobramento da estratégia.",tag:"Planejamento"},{front:"Planejamento operacional",back:"Curto prazo, tarefas, rotinas e procedimentos específicos.",tag:"Planejamento"},{front:"Macroambiente",back:"Forças demográficas, econômicas, tecnológicas, socioculturais e político-legais.",tag:"Organização"},{front:"Microambiente",back:"Clientes, fornecedores, concorrentes e novos entrantes.",tag:"Organização"},{front:"Trio primário da logística",back:"Transportes, manutenção de estoques e processamento de pedidos.",tag:"Logística"},{front:"Pareto / curva ABC",back:"Poucos itens concentram grande parcela do valor ou movimentação.",tag:"Materiais"},{front:"TIR e TMA",back:"O projeto é aceitável quando a TIR supera a taxa mínima de atratividade.",tag:"Finanças"},{front:"Empenho",back:"Ato que cria obrigação de pagamento, pendente ou não de condição.",tag:"Orçamento"},{front:"Liquidação",back:"Verifica o direito adquirido pelo credor com base em títulos e documentos.",tag:"Orçamento"},{front:"Ordem de pagamento",back:"Despacho da autoridade competente determinando que a despesa seja paga.",tag:"Orçamento"},{front:"Pregoeiro x autoridade",back:"O pregoeiro conduz; a autoridade homologa e promove a contratação.",tag:"Licitações"},{front:"Lei 14.133: sequência",back:"A habilitação pode ser antecipada por ato motivado e previsão editalícia.",tag:"Licitações"},{front:"Pena da Comissão de Ética",back:"Censura, fundamentada em parecer e com ciência do faltoso.",tag:"Ética"},{front:"Vida privada e função pública",back:"Integram-se; a conduta privada pode repercutir no conceito funcional.",tag:"Ética"},{front:"Escalas gráficas",back:"Formulário de dupla entrada: fatores nas linhas e graus nas colunas.",tag:"Pessoas"},{front:"Incidentes críticos",back:"Foco em desempenhos excepcionalmente positivos ou negativos.",tag:"Pessoas"},{front:"PROCV",back:"Busca um argumento na coluna e devolve valor correspondente de outra coluna.",tag:"Excel"},{front:"CONT.SE",back:"Conta células de um intervalo que atendem a um critério.",tag:"Excel"},{front:"Alerta: absoluto",back:"Todo, nenhum, sempre, somente, estritamente: procure exceção legal ou conceitual.",tag:"Linguagem"},{front:"Alerta: agente",back:"A ação pode existir, mas ser competência de outra autoridade.",tag:"Linguagem"},{front:"Alerta: lista",back:"Um único intruso torna falsa toda alternativa ligada por “e”.",tag:"Linguagem"},{front:"Alerta: EXCETO",back:"Reescreva o comando: procuro a única alternativa que não pertence ao grupo.",tag:"Linguagem"}
];

export const makeConfig=(code:string,title:string,accent:string,description:string,tone:string,scope:string):NotebookConfig=>({code,eyebrow:"IFMT · Administrador · prova oficial 2023",title,titleAccent:accent,description,tone,scope,bankProfile,statementMode,references:["IFMT — Prova de Administrador, Edital nº 133/2023.","IFMT — Gabarito definitivo do Edital nº 133/2023 (questões 56 e 57 anuladas e excluídas).","Caderno temático anexado — ordenação por matéria e assunto, 100 questões COCP/IFMT.","Descrição de atribuições do cargo de Administrador fornecida pelo usuário."]});
