import Link from "next/link";

const books = [
  {href:"/pressman",code:"01",edition:"8ª edição · capítulos 2 e 4",title:"Engenharia de Software",author:"Pressman & Maxim",description:"Processo, métodos, modelos prescritivos e evolucionários em questões comentadas.",stats:["18 questões","32 cards","3 níveis"],tone:"pressman"},
  {href:"/uml",code:"02",edition:"3ª edição · diagramas UML 2",title:"UML 2: Uma abordagem prática",author:"Gilleanes T. A. Guedes",description:"Classificação de diagramas e leitura de interações, com foco em sequência, comunicação e temporização.",stats:["18 questões","7 com figuras","16 cards"],tone:"uml"},
  {href:"/padroes",code:"03",edition:"GoF · padrões selecionados",title:"Padrões de Projeto",author:"Gamma, Helm, Johnson & Vlissides",description:"Intenção, aplicabilidade e diferenças entre padrões de criação e comportamentais.",stats:["12 questões","18 cards","2 exemplos oficiais"],tone:"patterns"},
  {href:"/recursividade",code:"04",edition:"Java · Fibonacci recursivo",title:"Recursividade em Java",author:"Algoritmos e rastreamento de execução",description:"Casos-base, pilha de chamadas, BigInteger e memorização da sequência de Fibonacci.",stats:["12 questões","18 cards","F(0) a F(12)"],tone:"recursion"},
  {href:"/ordenacao",code:"05",edition:"PHP 8 · sort e flags",title:"Ordenação e Funções Nativas",author:"Arrays, comparação natural e estabilidade",description:"SORT_NATURAL, SORT_FLAG_CASE, desempate alfanumérico e ordenação estável no PHP 8.",stats:["12 questões","18 cards","PHP 8"],tone:"sorting"},
  {href:"/fatorial",code:"06",edition:"Python 3.11 · recursão",title:"Fatorial em Python",author:"Rastreamento, pilha e casos-base",description:"Expansão e retorno de chamadas recursivas, complexidade e tratamento de entradas.",stats:["12 questões","18 cards","0! a 10!"],tone:"factorial"},
  {href:"/migracao-bd",code:"07",edition:"MySQL ↔ MariaDB",title:"Compatibilidade e Migração",author:"Gerenciamento de Banco de Dados",description:"Drop-in replacement, conectores, InnoDB, interoperabilidade e validação segura de migrações.",stats:["12 questões","18 cards","MariaDB Docs"],tone:"database"},
  {href:"/poo-java",code:"08",edition:"Java · POO",title:"Encapsulamento e Herança",author:"Modificadores de acesso",description:"private, protected, getters, setters, construtores e especialização de classes.",stats:["13 questões","18 cards","Java"],tone:"oop"},
  {href:"/arvore-busca-c",code:"09",edition:"Linguagem C · ABB",title:"Árvore Binária de Busca",author:"Estruturas de Dados e Recursão",description:"Inserção, busca, percurso em ordem, ponteiros e comportamento diante de valores duplicados.",stats:["12 questões","18 cards","C"],tone:"tree"},
  {href:"/polimorfismo-java",code:"10",edition:"Deitel · Java 8ª edição",title:"Polimorfismo em Java",author:"Classes abstratas, final e ligação dinâmica",description:"Referências de superclasse, sobrescrita, despacho em tempo de execução e hierarquias abstratas.",stats:["12 questões","18 cards","Capítulo 10"],tone:"polymorphism"},
  {href:"/grafos-cormen",code:"11",edition:"Cormen · 3ª edição",title:"Algoritmos de Grafos",author:"Ordenação, AGM e caminhos mínimos",description:"Ordenação topológica, Kruskal, conjuntos disjuntos e Dijkstra em questões comentadas.",stats:["12 questões","18 cards","Capítulos 22–24"],tone:"graph"},
  {href:"/condicionais-c",code:"12",edition:"Linguagem C · decisões",title:"Condicionais e Refatoração",author:"Equivalência lógica e fluxo de controle",description:"if/else, tabela de decisão, retornos antecipados e otimizações que preservam comportamento.",stats:["12 questões","18 cards","C"],tone:"conditionals"},
  {href:"/operadores-logicos",code:"13",edition:"Puga · capítulo 3",title:"Operadores e Expressões",author:"Lógica de Programação",description:"Atribuição, comparação, operadores lógicos, tabelas-verdade e precedência em Java e pseudocódigo.",stats:["12 questões","18 cards","Java"],tone:"operators"},
  {href:"/banco-dados-fundamentos",code:"14",edition:"Heuser · Elmasri & Navathe · Date",title:"Fundamentos e Modelagem de Dados",author:"Do minimundo ao esquema",description:"Projeto conceitual, lógico e físico, arquitetura de três esquemas, MER, modelo relacional, álgebra e normalização.",stats:["11 oficiais","16 cards","1 figura"],tone:"database-foundations"},
  {href:"/sql-transacoes",code:"15",edition:"SQL · arquivos · recuperação",title:"SQL, Transações e Segurança",author:"Da consulta à continuidade",description:"Agregação, sublinguagens SQL, transações, organização de arquivos, backup, recuperação e controle de acesso.",stats:["12 oficiais","16 cards","BD2"],tone:"sql-notebook"},
  {href:"/bi-data-warehouse",code:"16",edition:"DW · ETL · OLAP · Data Mining",title:"BI e Dados Analíticos",author:"Do histórico à decisão",description:"Data Warehouse, aquisição de dados, operações multidimensionais, pré-processamento e descoberta de conhecimento.",stats:["10 oficiais","16 cards","BD3"],tone:"analytics-notebook"},
  {href:"/legislacao-educacional-ebtt",code:"17",edition:"IFMT · prova EBTT 2023",title:"Educação, Legislação e Carreira",author:"Constituição · LDB · Rede Federal · IFMT",description:"Direitos educacionais, organização acadêmica, carreira EBTT, ética e inclusão com RAIO-X artigo por artigo.",stats:["10 oficiais","16 cards","RAIO-X duplo"],tone:"education-notebook"},
  {href:"/mato-grosso-transversais",code:"18",edition:"IFMT · prova 2023 + atualização 2026",title:"Mato Grosso e Transversais",author:"Território, sociedade, natureza e economia",description:"Prova anterior e bloco prospectivo sobre os polos do concurso, expansão do IFMT, produção e ambiente.",stats:["10 oficiais + 12 atuais","1 figura","32 cards"],tone:"mato-grosso-notebook"},
  {href:"/lingua-portuguesa",code:"19",edition:"IFMT · última prova + 225 questões mapeadas",title:"Língua Portuguesa",author:"Gramática, semântica e eliminação de alternativas",description:"Faça e refaça as dez questões da última prova com regra básica, análise do comando e pistas para eliminar distratores.",stats:["10 oficiais","2 tirinhas","24 cards"],tone:"portuguese-notebook"},
];

export default function LibraryHome(){return <main className="libraryPage">
  <header className="libraryHeader"><Link className="brand" href="/"><span>ES</span>Cadernos de Estudo</Link><div>Engenharia de Software · biblioteca de questões</div></header>
  <section className="libraryHero"><div className="eyebrow">Escolha um caderno</div><h1>Do livro à questão.<br/><em>Do erro ao conceito.</em></h1><p>Cada caderno usa um banco próprio, limitado à obra de referência e aos assuntos cobrados nas questões-modelo.</p></section>
  <section className="bookShelf" aria-label="Livros disponíveis">{books.map(book=><Link href={book.href} className={`bookTile ${book.tone}`} key={book.href}>
    <div className="bookTop"><span>{book.code}</span><small>{book.edition}</small></div><div className="bookBody"><p>{book.author}</p><h2>{book.title}</h2><div>{book.description}</div></div><div className="bookFoot"><ul>{book.stats.map(item=><li key={item}>{item}</li>)}</ul><strong>Abrir caderno →</strong></div>
  </Link>)}</section>
  <footer className="libraryFooter"><span>Conteúdo educacional baseado nas referências indicadas.</span><span>Novos livros podem ser adicionados à estante.</span></footer>
</main>}
