
import Link from 'next/link';
import catalog from '../data/study-catalog.json';
import { commercialOffer, checkoutUrl } from '../lib/commercial-offer';

const collections = [
  { id: '01', title: 'Computação e engenharia', subtitle: 'DO CONCEITO AO CÓDIGO', description: 'Engenharia de software, UML, padrões de projeto, programação, algoritmos e bancos de dados.', href: '/pressman', cover: 'Engenharia\nde Software', tone: 'teal', label: 'Explorar um caderno' },
  { id: '02', title: 'IFMT e Administração', subtitle: 'CONHECIMENTO PARA A PROVA', description: 'Português, legislação educacional, Mato Grosso, gestão pública, pessoas e processos.', href: '/acervo', cover: 'Administração\ne Concursos', tone: 'sand', label: 'Ver o acervo' },
  { id: '03', title: 'SEMA-MT · Tecnologia da Informação', subtitle: 'PRÁTICA COM PLANEJAMENTO', description: 'Questões e trilha de preparação para Analista em Tecnologia da Informação. Consulte a cobertura de cada assunto.', href: '/sema-mt-ti', cover: 'Tecnologia da\nInformação', tone: 'blue', label: 'Conhecer a trilha' },
];

function BookCover({ title, tone, number }: { title: string; tone: string; number: string }) {
  return <div className={`saleBook ${tone}`} aria-hidden="true"><span>CADERNOS DE ESTUDO</span><div className="saleBookPattern"><i/><i/><i/><i/></div><strong>{title}</strong><small>QUESTÕES · CONCEITOS · REVISÃO</small><b>{number}</b></div>;
}

export default function Home() {
  const checkout = checkoutUrl();
  const commented = catalog.filter(q => q.explanation?.trim()).length;
  return <main className="commercialPage salePage">
    <div className="saleTopline"><span>UM CONCEITO POR VEZ. UMA REVISÃO MAIS CONSCIENTE.</span><Link href="/aluno">Já conhece o material? Acessar estudos ↗</Link></div>
    <header className="commercialNav"><Link href="/" className="commercialBrand"><span>CE</span><div>Cadernos de Estudo<small>BIBLIOTECA DIGITAL INTERATIVA</small></div></Link><nav aria-label="Navegação principal"><a href="#conteudo">O material</a><a href="#duvidas">Dúvidas</a><Link href="/aluno">Área de estudo ↗</Link></nav></header>
    <div className="saleLayout">
      <div className="saleProduct">
        <section className="saleIntro"><p className="commercialEyebrow">ESTUDE PARA ENTENDER. REVISE PARA LEMBRAR.</p><h1>Da questão ao<br/><em>conhecimento.</em></h1><p className="commercialLead">Cadernos interativos para conectar conceitos, prática e revisão na sua preparação.</p>
          <div className="saleShowcase"><div className="saleShowcaseLabel"><span>SEU ACERVO DE ESTUDO</span><span>NO NAVEGADOR ↗</span></div><div className="saleBookCollection">{collections.map(item=><BookCover key={item.id} title={item.cover} tone={item.tone} number={item.id}/>)}</div><div className="saleShowcaseFoot"><span>Computação</span><span>IFMT e Administração</span><span>SEMA-MT · TI</span></div></div>
        </section>
        <section className="saleIncluded" id="conteudo"><p className="commercialEyebrow">CONHEÇA AS FRENTES DO ACERVO</p>{collections.map(item=><article className="saleIncludedRow" key={item.id}><BookCover title={item.cover} tone={item.tone} number={item.id}/><div><span className="saleItemLabel">{item.subtitle}</span><h2>{item.title}</h2><p>{item.description}</p><Link href={item.href}>{item.label} →</Link></div><span className="saleCheck" aria-hidden="true">✓</span></article>)}
          <div className="saleCollectionTotal"><strong>{catalog.length.toLocaleString('pt-BR')}</strong><div>questões no catálogo atual<span>{commented.toLocaleString('pt-BR')} com explicação cadastrada</span></div></div><p className="commercialNote">Questões de provas e exercícios autorais. A cobertura e os comentários variam por caderno; alguns itens exigem consulta à fonte original. Confira o material antes de escolher.</p>
        </section>
      </div>
      <aside className="salePurchase" aria-label="Oferta e acesso ao material"><div className="salePurchaseCard"><div className="salePurchaseHeading"><span className="commercialEyebrow">SEU PRÓXIMO PASSO</span><span className="saleAccessTag">ACESSO ONLINE</span></div><h2>{checkout ? 'Comece sua preparação.' : 'Conheça por dentro.'}</h2><p>{checkout ? commercialOffer.summary : 'Abra um caderno e experimente o formato de estudo antes de escolher.'}</p><div className="saleOfferName"><span>O MATERIAL</span><strong>{commercialOffer.name}</strong></div><ul className="saleBenefits"><li>Questões para praticar conceitos</li><li>Explicações disponíveis por caderno</li><li>Cards de memorização nos cadernos</li><li>Revisão a partir do seu histórico</li></ul>{checkout && commercialOffer.priceLabel && <p className="salePrice">{commercialOffer.priceLabel}</p>}{checkout ? <a className="commercialButton" href={checkout}>Ver condições e comprar →</a> : <Link className="commercialButton" href="/pressman">Experimentar o caderno →</Link>}<Link className="saleBrowseLink" href="/acervo">Consultar todo o acervo</Link><div className="saleAvailability"><span aria-hidden="true">ⓘ</span><p>{checkout ? commercialOffer.deliveryDescription : 'As vendas ainda não estão abertas. Preço, prazo de acesso e condições serão informados na oferta.'}</p></div></div>
        <div className="saleDelivery"><span aria-hidden="true">↗</span><p><strong>Seu estudo acompanha você.</strong><br/>Acesse pelo navegador do celular ou computador, com conexão à internet.</p></div>
        <div className="saleQuickFaq"><details><summary>Preciso criar uma conta?</summary><p>Você pode explorar os cadernos. Para salvar progresso e anotações entre sessões, entre com sua conta ChatGPT.</p></details><details><summary>São aulas em vídeo ou PDFs?</summary><p>O formato principal é uma plataforma de cadernos interativos. Não inclui aulas em vídeo. Consulte em cada caderno os materiais disponíveis.</p></details><details><summary>Todas as questões são comentadas?</summary><p>Há {commented.toLocaleString('pt-BR')} questões com explicação cadastrada. Outros itens podem conter apenas gabarito ou depender de consulta à fonte original.</p></details></div>
      </aside>
    </div>
    <section className="saleMethod"><div><p className="commercialEyebrow">UM MÉTODO, TRÊS MOVIMENTOS</p><h2>Do erro ao conceito.<br/>Do conceito à revisão.</h2></div><ol><li><span>01</span><strong>Pratique</strong><p>Responda antes de consultar o conteúdo. Observe suas dúvidas.</p></li><li><span>02</span><strong>Compreenda</strong><p>Consulte explicações e referências disponíveis no caderno.</p></li><li><span>03</span><strong>Retome</strong><p>Use seu histórico para decidir o que precisa de outra revisão.</p></li></ol></section>
    <section className="commercialSection saleFaqSection" id="duvidas"><div><p className="commercialEyebrow">ESCOLHA COM CLAREZA</p><h2>Antes de começar.</h2><p>Conheça o formato e as condições do material.</p></div><div className="commercialFaq"><details><summary>O material cobre todo o edital?</summary><p>A cobertura varia entre os cadernos. Compare os assuntos disponíveis com o seu edital e use as referências indicadas para complementar os estudos. Não há promessa de aprovação.</p></details><details><summary>Como funciona a revisão?</summary><p>A área de estudo permite praticar questões e retomar itens do seu histórico. O progresso salvo depende de login com sua conta ChatGPT.</p></details><details><summary>Como recebo acesso após a compra?</summary><p>{checkout ? commercialOffer.deliveryDescription : 'O formato de entrega, o prazo de acesso e as condições de compra serão apresentados quando a oferta estiver disponível. Por enquanto, você pode conhecer a demonstração.'}</p></details><details><summary>Os recursos de inteligência artificial estão incluídos?</summary><p>Recursos de IA dependem de disponibilidade e configuração. Consulte as condições da oferta antes de contratar; a demonstração permite conhecer o formato dos cadernos.</p></details></div></section>
    <footer className="commercialFooter"><div><strong>Cadernos de Estudo</strong><p>Prática, conceitos e continuidade.</p></div><div><Link href="/referencias">Referências e método</Link><Link href="/acervo">Acervo</Link>{commercialOffer.supportEmail && <a href={`mailto:${commercialOffer.supportEmail}`}>Suporte</a>}<span>Material educacional independente.</span></div></footer>
  </main>;
}
