import data from '../data/admin-bank.json';
type SeedQuestion={id:string;number:number;tecId:string;source:string;subject:string;prompt:string;options:string[];answer:number;bibliography?:string;explanation?:string;sourceUrl?:string;referenceText?:string;bankAnalysis?:string;reviewStatus?:'reviewed'|'needs_review';suggestedAnswer?:number;optionAnalysis?:string[]};
export const bankSeed=data as {questions:SeedQuestion[]};
type Entry={id:string;kind:string;title:string;authors:string;label:string;qs:number[];url?:string;locator?:string};
export const sourceSeed:Entry[]=[
 {id:'ballou-1993',kind:'book',title:'Referência a Ballou (título não informado no enunciado)',authors:'Ronald H. Ballou',label:'1993 · edição a conferir',qs:[1]},
 {id:'melo-2011',kind:'document',title:'A gestão da demanda em cadeias de suprimentos: uma abordagem além da previsão de vendas',authors:'Daniela de Castro Melo; Rosane Lúcia Alcântara (grafia a conferir)',label:'Gestão & Produção, v.18, n.4, 2011',qs:[4],locator:'p. 812–813, conforme enunciado'},
 {id:'colli-2022',kind:'book',title:'Gestão patrimonial: aspectos tributários',authors:'Nicolli Anversa Colli',label:'Almedina, 2022',qs:[5]},
 {id:'chiavenato-teorias',kind:'book',title:'Teorias da Administração (título conforme enunciado)',authors:'Idalberto Chiavenato',label:'Edição não informada',qs:[10,22]},
 {id:'cruz-2017',kind:'book',title:'Manual de planejamento estratégico: ferramentas para desenvolver, executar e aplicar',authors:'Tadeu Cruz',label:'Atlas, 2017',qs:[13]},
 {id:'ambrosio-bcg',kind:'document',title:'A matriz BCG passo a passo',authors:'A. Ambrósio; V. Ambrósio',label:'Revista da ESPM, v.12, n.4, 2012 (conforme enunciado)',qs:[13]},
 {id:'chiavenato-planejamento',kind:'book',title:'Planejamento estratégico: a nova jornada da intenção aos resultados',authors:'Idalberto Chiavenato',label:'5ª ed., Atlas, 2023',qs:[15]},
 {id:'silva-teorias',kind:'book',title:'Teorias da Administração',authors:'Reinaldo O. da Silva',label:'Edição não informada',qs:[16,31]},
 {id:'oliveira-planejamento',kind:'book',title:'Planejamento Estratégico',authors:'Djalma de Pinho Rebouças de Oliveira',label:'Edição não informada',qs:[17]},
 {id:'ifmt-pdi-2019',kind:'document',title:'Plano de Desenvolvimento Institucional — IFMT',authors:'IFMT',label:'2019–2023 (período a conferir na Q34)',qs:[17,34]},
 {id:'chiavenato-tga',kind:'book',title:'Introdução à Teoria Geral da Administração',authors:'Idalberto Chiavenato',label:'Campus, edição transcrita como 7?',qs:[19],locator:'p. 81, 121–127, conforme enunciado'},
 {id:'goleman',kind:'book',title:'Desafios da liderança',authors:'Daniel Goleman',label:'Sextante, 2009',qs:[21]},
 {id:'bergue',kind:'book',title:'Gestão de pessoas: liderança e competências para o setor público',authors:'Sandro Trescastro Bergue',label:'Enap, 2019',qs:[21]},
 {id:'muniz',kind:'book',title:'Jornada Ágil de Liderança',authors:'Antonio Muniz et al.',label:'Brasport, 2020',qs:[21]},
 {id:'schermerhorn',kind:'book',title:'Obra não identificada no enunciado',authors:'Schermerhorn Júnior (grafia a conferir)',label:'2014',qs:[23]},
 {id:'hitt-miller',kind:'book',title:'Obra não identificada no enunciado',authors:'Hitt; Miller; Colella',label:'2015',qs:[24,30]},
 {id:'emmendoerfer',kind:'book',title:'Inovação e empreendedorismo no setor público',authors:'Magnus Luiz Emmendoerfer',label:'Enap, 2019',qs:[25]},
 {id:'chiavenato-pessoas',kind:'book',title:'Gestão de pessoas: o novo papel dos recursos humanos nas organizações',authors:'Idalberto Chiavenato',label:'Manole, 2014 (Q25 tem ano truncado)',qs:[25,27,32]},
 {id:'maximiano-2000',kind:'book',title:'Obra não identificada no enunciado',authors:'Antonio Cesar Amaru Maximiano',label:'2000',qs:[26]},
 {id:'robbins',kind:'book',title:'Comportamento Organizacional',authors:'Stephen Robbins',label:'Edição não informada',qs:[28,29]},
 {id:'mcasp-11',kind:'document',title:'Manual de Contabilidade Aplicada ao Setor Público — MCASP',authors:'Secretaria do Tesouro Nacional',label:'11ª ed., 2024',qs:[38]},
 {id:'mcasp-9',kind:'document',title:'Manual de Contabilidade Aplicada ao Setor Público — MCASP',authors:'Secretaria do Tesouro Nacional',label:'9ª ed.',qs:[39,40,42,47,58]},
 {id:'mcasp-8',kind:'document',title:'Manual de Contabilidade Aplicada ao Setor Público — MCASP',authors:'Secretaria do Tesouro Nacional',label:'8ª ed.',qs:[41]},
 {id:'ostroski',kind:'book',title:'Orçamento Público',authors:'Sinésio Stéfano Dubiela Ostroski',label:'2010',qs:[49]},
 {id:'franco-neto',kind:'book',title:'Centralização de compras públicas no Brasil',authors:'Eduardo Grossi Franco Neto',label:'Thoth, 2023',qs:[74]},
 {id:'berk-demarzo',kind:'book',title:'Finanças Empresariais',authors:'Jonathan Berk; Peter DeMarzo',label:'Bookman, 2009',qs:[102],locator:'p. 385–419, conforme enunciado'},
 {id:'pmbok',kind:'document',title:'PMBOK — referência do enunciado',authors:'Project Management Institute',label:'2011 · edição não informada',qs:[104]},
 {id:'maximiano-veroneze-2024',kind:'book',title:'Gestão de Projetos: preditiva, ágil e estratégica',authors:'Antonio Cesar Amaru Maximiano; Fernando Veroneze',label:'6ª ed., Atlas, 2024',qs:[105]},
 {id:'maximiano-veroneze-2022',kind:'book',title:'Gestão de Projetos: preditiva, ágil e estratégica',authors:'Antonio Cesar Amaru Maximiano; Fernando Veroneze',label:'Atlas, 2022',qs:[106]},
 {id:'kerzner',kind:'book',title:'Gestão de Projetos: as melhores práticas',authors:'Harold Kerzner',label:'2017',qs:[107]},
 {id:'lei-11892',kind:'law',title:'Lei nº 11.892/2008 — Rede Federal',authors:'Brasil',label:'Redação citada na prova · a conferir',qs:[6],url:'https://www.planalto.gov.br/ccivil_03/_ato2007-2010/2008/lei/l11892.htm'},
 {id:'cf1988',kind:'law',title:'Constituição Federal de 1988',authors:'Brasil',label:'Redação citada nas provas · a conferir',qs:[25,40,41],url:'https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm'},
 {id:'lei-4320',kind:'law',title:'Lei nº 4.320/1964',authors:'Brasil',label:'Redação citada nas provas · a conferir',qs:[40,41,43,47,50,51,52,53,54,55,56,57,58],url:'https://www.planalto.gov.br/ccivil_03/leis/l4320.htm'},
 {id:'lc-101',kind:'law',title:'Lei Complementar nº 101/2000 — LRF',authors:'Brasil',label:'Redação citada nas provas · a conferir',qs:[46,48,59,60,61,62,63,64,65,66],url:'https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp101.htm'},
 {id:'lei-14133',kind:'law',title:'Lei nº 14.133/2021 — Licitações e contratos',authors:'Brasil',label:'Redação citada nas provas · a conferir',qs:Array.from({length:17},(_,i)=>i+67),url:'https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2021/lei/l14133.htm'},
 {id:'decreto-1171',kind:'law',title:'Decreto nº 1.171/1994 — Código de Ética',authors:'Brasil',label:'Redação citada nas provas · a conferir',qs:[...Array.from({length:17},(_,i)=>i+84),101],url:'https://www.planalto.gov.br/ccivil_03/decreto/d1171.htm'},
 {id:'decreto-6029',kind:'law',title:'Decreto nº 6.029/2007 — Sistema de Gestão da Ética',authors:'Brasil',label:'Redação citada na prova · a conferir',qs:[101],url:'https://www.planalto.gov.br/ccivil_03/_ato2007-2010/2007/decreto/d6029.htm'},
 {id:'ifmt-091',kind:'document',title:'Resolução CONSUP IFMT nº 091/2014',authors:'IFMT',label:'2014 · arquivo a conferir',qs:[88]},
];
