export type BankQuestion={id:string;number:number;tecId:string;source:string;subject:string;prompt:string;options:string[];answer:number;explanation?:string;reviewNote?:string;analyses?:string[];citations?:Citation[]};
export type Citation={id:string;title:string;kind:string;label:string;locator:string;role:string;verified:number;official_url:string;note:string};
export class HttpError extends Error { constructor(public status:number,message:string){super(message);} }
export function field(value:unknown,name:string,max=1000,required=false){if(typeof value!=='string'){if(required)throw new HttpError(400,`${name}: obrigatório.`);return '';}const s=value.trim();if(s.length>max||required&&!s)throw new HttpError(400,`${name}: tamanho inválido.`);return s;}
export function choice(value:unknown,values:string[],name:string){if(typeof value!=='string'||!values.includes(value))throw new HttpError(400,`${name}: valor inválido.`);return value;}
export function date(value:unknown){const s=field(value,'Data',10);if(s&&(!/^\d{4}-\d{2}-\d{2}$/.test(s)||!Number.isFinite(Date.parse(s))))throw new HttpError(400,'Data inválida.');return s;}
export function safeUrl(value:unknown){const s=field(value,'Endereço',2000);if(!s)return '';try{const u=new URL(s);if(u.protocol!=='https:'||u.username||u.password)throw Error();return u.href;}catch{throw new HttpError(400,'Informe um endereço HTTPS válido.');}}
export function adminIdentity(request:Request,adminEmails:string|undefined){const email=request.headers.get('oai-authenticated-user-email')?.toLowerCase();const id=request.headers.get('oai-authenticated-user-id');const allow=(adminEmails??'').split(',').map(s=>s.trim().toLowerCase()).filter(Boolean);return id&&email&&allow.includes(email)?{id,email}:null;}
export function checkWriteOrigin(request:Request){if(request.headers.get('origin')!==new URL(request.url).origin)throw new HttpError(403,'Origem da solicitação não autorizada.');}
export function draftFromPassage(text:string,term:string){if(term.length<2||term.length>120||!text.includes(term))throw new HttpError(400,'Selecione um termo que exista no trecho.');const sentence=text.split(/(?<=[.!?])\s+/).find(s=>s.includes(term))??text;return {prompt:`Complete a lacuna de acordo com a fonte indicada:\n${sentence.replace(term,'__________')}`,correct:term,explanation:`O trecho da fonte registra: ${sentence}`};}
export function normalizeDraft(p:Record<string,unknown>){const prompt=field(p.prompt,'Enunciado',12000,true),subject=field(p.subject,'Assunto',300,true),explanation=field(p.explanation,'Justificativa',8000,true);if(!Array.isArray(p.options)||p.options.length!==5)throw new HttpError(400,'Informe cinco alternativas.');const options=p.options.map(v=>field(v,'Alternativa',3000,true));if(new Set(options.map(s=>s.toLowerCase())).size!==5)throw new HttpError(400,'As alternativas precisam ser diferentes.');const answer=Number(p.answer);if(!Number.isInteger(answer)||answer<0||answer>4)throw new HttpError(400,'Selecione o gabarito.');return {prompt,subject,explanation,options,answer};}
export function searchExpression(query:string){return (query.match(/[\p{L}\p{N}]+/gu)??[]).slice(0,12).map(s=>`"${s}"`).join(' AND ');}
